### ISSUE TITLE
How to migrate classic ngrx to ngrx-data

### ISSUE THREAD

**Issue by ylulloa** [johnpapa/angular-ngrx-data#148]
How to introduce this lib to an existing app? What would be the suggested strategy to set it up in the way that it's pointing to all the existing redux artifacts (actions, reducers, ...), as an initial step, so they can be removed piece by piece if not needed after having ngrx-data doing its magic.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
I would start with an empty `ngrx-data` example. Follow the example in the _README.md_. but with no metadata.  Then take a single, simple entity and try it, just like the `Hero` example.

Get that working. Rinse. Repeat.

I'm closing because issues are about problems or todos for the library.  I'm hoping others will join in providing guidance out on the web.

Best wishes.
