### ISSUE TITLE
Support for query parameter based views into collections

### ISSUE THREAD

**Issue by russoturisto** [johnpapa/angular-ngrx-data#166]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
entityAC1Selector = entityAService.getWithQuery({c: 1})
entityAC2Selector = entityAService.getWithQuery({c: 2})

### Expected/desired behavior
>
Entity collections should support views, each of which is associated with a particular set of query parameter/value pairs

### Mention any other details that might be useful
We are just starting to use ngrx-data and so far can't find a way to store more than one result in the same collection.  This is something that we need.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
I'm sorry but I think you may be confused about the difference between a _selector_ that _queries_ a cached collection and a _command_ that asks the server to retrieve data.

If you want to select the entities from cache whose `c` value is 2, you can write an observable selector

```
const c2Selector$ = entityAService.entities$.pipe(filter(a => a.c === 2));
```
Notice how I piped an RxJS `filter` operator onto the ngrx-data `entities$` observable selector.

Such piping is standard ngrx selector play and isn't about ngrx-data _per se_. It's just how you consume selectors in ngrx.

You can parameterize this approach to make a function that returns selectors$:
```
const cSelectorFn = (cValue: number) => entityAService.entities$.pipe(filter(a => a.c === cValue));
const c1Selector = cSelectorFn(1);
const c2Selector = cSelectorFn(2)
```


All of this ^^^ is quite different from how you got "A"s into your collection in the first place.  If you wanted all "A"s whose 'c' value is `1`, then you might write:
```
entityAService.getWithQuery({c: 1});
```
Traditionally, you'd subscribe to one of the selectors$ above to learn when those "A"s arrived.
As of Beta.8 you can subscribe to the observable returned by `getWithQuery`

```
entityAService.getWithQuery({c: 1}).subscribe(data => console.log('"A"s with c:1", data));
```

Please let me know if this clarifies.

**Comment by russoturisto** [comment]
Thank you, this does clarify the model behind the framework.   We should be able to work with this model in majority of the cases.  We do have one additional concern.

Given:

 class EntityA {
  id
  bs: EntityB[]
}
class EntityB {
  id
  entityAId
  cs: EntityC[]
}
class EntityC {
  id
  entityBId
}

Having a list of entityAIds we would like to query for EntityAs and related EntityCs by those ids.  We would like to do so at the same time, without having to first wait for EntityA responses.

In that case, we build our EntityC service to accept entityAId as an input parameter and do a join with EntityB to get the needed records.

Then, when the user comes back to the same view, we want the selector used on that view to get us all EntityCs that were associated with the listed EntityAs at the time of last server request  (and make a subsequent request to refresh the data).

Thank you very much for your time! :)

**Comment by wardbell** [comment]
This is the widely known **entity navigation** problem ... a problem for all NoSQL approaches, btw, because relations are not directly supported.

Search the web for discussions of normalizing your Ngrx/Redux entity models. There are tools to help but I haven't used them. I just do it.

I wish I had great documentation for you. I don't (yet).

The approach I'm taking can be summarized:
1) Normalize your entity data (true for all ngrx/redux, not just ngr-data)
2) Create selectors$ that effectively perform the joins that you need in memory. 
3) Subscribe (or async pipe them) when you need them.

"Normalize" means that you do NOT have related-entity arrays in your model. It should look like
```
class EntityA {
  id
}
class EntityB {
  id
  entityAId
}
class EntityC {
  id
  entityBId
}
```
The selectors$ construct a **ViewModel** of the portion of the graph you care about by combining and filtering the observable selectors of the constituent entity types. Yes, this is a mouthful and I don't have time right now to show you what I mean. I'm just trying to outline the plan of attack for you. Others may have tackled this already and described how to do it (I know it's on the list of ngrx "to dos"). There's an ngConf 2018 talk on selectors that is worth viewing as well.

You can create as many of these relationship selectors$ as you want. I would create factories for them such that I get something like `EntityAService.theAgraph$(idOfA: 42)`. That would return an observable of an A graph that is populated with Bs (and those Bs with Cs if necessary).

Remember this result is a **ViewModel**. You cannot and must not mutate them. When you make a change to a nested `C` entity, you call the `cService` to update that and rely on the relationship selectors to rebuild the composite object graph.

That's all I have time to say in this space (which, to be fair to me ... and who better to be fair to :-) ... is dedicated to ngrx-data issues rather than instruction).

HTH.

**Comment by russoturisto** [comment]
Understood, thank you much :)

**Comment by wardbell** [comment]
Closing because not actionable. But well worth our discussion.
