### ISSUE TITLE
How to compare previous state with new state?

### ISSUE THREAD

**Issue by brandondtran** [johnpapa/angular-ngrx-data#188]
When subscribing to entities$ or entityMap$, we are given the new entities, but not the previous entities.  Is there a way to get the previous entities to compare changes?

I know there is changeState$ selector, but it doesn't seem to ever return anything except an emby object.  Is this still a work in progress?

**Comment by wardbell** [comment]
The `changeState$` tells you about unsaved changes that you are accumulating either through direct updates to cache OR because you are in the middle of a pessimistic save and the server has not responded.

>You will also have changeState if an optimistic save failed. It's up to you to decide what to do when it fails which may or may not involve reverting this changesState.

If you want the prior state, you can pipe on the RxJS  `pairwise` operator as described here:
https://stackoverflow.com/questions/50059622/rxjs-observable-which-emits-both-previous-and-current-value-starting-from-first

It's all about learning RxJS :-)
