### ISSUE TITLE
How to create custom selectors for an EntityCollectionService?

### ISSUE THREAD

**Issue by brandondtran** [johnpapa/angular-ngrx-data#193]
- I have an entity collection "Dog"
- I want to create a boolean selector called areTenDogsLoaded$
- So I may do the following: entityServices.getEntityCollectionService('Dog').areTenDogsLoaded$.subscribe()

How can I do such a thing?

Thanks

**Comment by alekline** [comment]
Did you find any good / simple example of how to do this?

**Comment by alekline** [comment]
I fixed the problem but I am not entirely sure this is the best way to do it, because I understand this is not a real `selector`, but just a functions this kind of hacking into the store..

 - If i understand ngrx-data correctly, you have "register" the custom selectors$ that you create in `EntityCollectionService.selectors$` somehow.

My fix: Please share if you have any thoughts
---------------------------------------------------------------------------
I created a method in my `hero.service.ts` file that takes parts of the state from the `entities$` observable:

from: https://github.com/johnpapa/ngrx-data-lab/blob/master/README.md (also similar to the example in https://github.com/johnpapa/angular-ngrx-data/blob/master/docs/entity-collection-service.md)
  - I took the Observable `heroeService.entities$`  
```
constructor(private heroService: HeroService) {
  this.heroes$ = heroService.entities$;
}
```

 -  And did this:
```
constructor(private heroService: HeroService) {
  this.heroesNames$ = heroService.entities$
      .pipe(map((heroesEntities) => this.extractHeroesNames(heroesEntities)));

}

private extractHeroesNames(heroesEntities) {
  console.log('heroEntities is a list: ', heroesEntities);

  var heroNamesList: any[] = [];
  for (let i=0; i<heroesEntities.length; i++) {
    let heroNameOnly = {
      name:       heroesEntities[i].name,
    }
    heroNamesList.push(heroNameOnly);
  }

  console.log('Complete list of heroNamesList', heroNamesList);
  return heroNamesList;
}
```

Is this the correct approach?
