### ISSUE TITLE
Request getByKey() option check if in Store 

### ISSUE THREAD

**Issue by jberall** [johnpapa/angular-ngrx-data#200]
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Have another query or flag to check if the recordset is in the store.
If in the store not go to the server.

Also, If anyone has code on how to achieve this that would be greatly appreciated.

Thanks,

**Comment by wardbell** [comment]
It's not a bad idea to add the option. But I'm inclined not to complicate the library with this special exception. No other methods have a _check-cache-first_ option. And once you start down this path, you want more options ("Get from cache and then refresh". "Get from cache unless the cached version is expired". etc).

It's fairly easy to implement this yourself. Imagine the following extension to the `HeroService`

```
import { Observable, of } from 'rxjs';
import { exhaustMap, map, ... } from 'rxjs/operators';
  ...
  /** Get Hero by id, from cache if it is there, else look in the database */
  getByKeyCacheFirst(id: number): Observable<Hero> {
    return this.entityMap$.pipe( // entityMap$ is a dictionary of the entity type, keyed by id
      map(heroMap => heroMap[id]),
      exhaustMap(hero => {
        // TODO: error handling
        return hero ? of(hero) : this.getByKey(id);
      })
    );
  }
```
There's a pattern to follow if you wanted to make it generic in your app.

Btw, using `exhaustMap` because don't want to keep stacking up calls to the server when already waiting for the requested hero to be returned.

I'm closing this issue because we have no plans to pursue your request. If you think we should reopen, please create a new issue that references this one.

And thanks for trying ngrx-data.

**Comment by jberall** [comment]
`
If anyone else is interested in getting all the cache first.
  getAllCacheFirst(
    // tslint:disable-next-line:no-any
    entityService: EntityCollectionService<any>
    // tslint:disable-next-line:no-any
  ): Observable<any> {
    return entityService.entityMap$.pipe(
      exhaustMap(entity => {
        // TODO: error handling
        return Object.keys(entity).length
          ? entityService.entities$
          : entityService.getAll();
      }),
      take(1)
    );
  }
`

**Comment by SerkanSipahi** [comment]
@jberall please format your post correctly! its difficult to read, thanks.
