### ISSUE TITLE
Get Data from SQL Server instead of Inmemory Database

### ISSUE THREAD

**Issue by joharzmn** [johnpapa/angular-ngrx-data#205]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
Failed to load resource: the server responded with a status of 404 (Not Found)

Actually the url of my .net core api is different from what is called by ngrx-data by default.
>

### Expected/desired behavior
I was using ngrx-data with inmemorydataservice and it was working fine. But now i want to get data from SQL Database using Asp.net Core Apis.  
>

### OS and Version?
> Windows 10
### Versions
>

### Mention any other details that might be useful
How can i change the url of api which is called by ngrx to look like the url of my .net core api?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
Please read the doc on configuring the `DefaultDataService` [here](https://github.com/johnpapa/angular-ngrx-data/blob/master/docs/entity-dataservice.md#configure-the-defaultdataservice) which explains how to set the `root` configuration property.

Closing because I believe you'll find all you need there. Open a new issue, referencing this one, if you need more help or have a suggestion.

Thanks for trying ngrx-data.
