### ISSUE TITLE
Consider immutable JS

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/angular-ngrx-data#34]

**Comment by wardbell** [comment]
Or `immer.js`

But do we need it?  `@ngrx/entity` does NOT use an immutable library to improve performance. I think they have something cooking with `freeze` to prevent mutation.

**Comment by dolanmiu** [comment]
Sorry to bring back an old thread but,

Is it good practice to use an immutable library like `immutable.js` in `@ngrx` then?

Surely it's better for guaranteed safety... otherwise a lot of discipline is required to ensure immutability (which gets harder on bigger teams)

Or do you guys feel its unnecessary and plain JS objects are sufficient?
